// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tR0ZNkC_KfnWX2FmAqvceDiLnBPHXW0',
    appId: '1:574488824195:web:a46e789518d698bfa20eb6',
    messagingSenderId: '574488824195',
    projectId: 'auth-tutorial-759e6',
    authDomain: 'auth-tutorial-759e6.firebaseapp.com',
    storageBucket: 'auth-tutorial-759e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjtQjI5HXu2XbHqFjGVrBQMIu99uRzrA',
    appId: '1:574488824195:android:f1dc3a48bc4c497fa20eb6',
    messagingSenderId: '574488824195',
    projectId: 'auth-tutorial-759e6',
    storageBucket: 'auth-tutorial-759e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8zIm1E4DtCF3gSfYqN8pdCkB2QB1sRD0',
    appId: '1:574488824195:ios:6ff75f5ca08eed46a20eb6',
    messagingSenderId: '574488824195',
    projectId: 'auth-tutorial-759e6',
    storageBucket: 'auth-tutorial-759e6.appspot.com',
    iosClientId: '574488824195-8614slm92cuhmsant6vsdj7nd62i4n5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.queryPosts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8zIm1E4DtCF3gSfYqN8pdCkB2QB1sRD0',
    appId: '1:574488824195:ios:6ff75f5ca08eed46a20eb6',
    messagingSenderId: '574488824195',
    projectId: 'auth-tutorial-759e6',
    storageBucket: 'auth-tutorial-759e6.appspot.com',
    iosClientId: '574488824195-8614slm92cuhmsant6vsdj7nd62i4n5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.queryPosts',
  );
}
